### ISSUE TITLE
cryptography.fernet.InvalidToken InvalidToken

### ISSUE THREAD

**Issue by siddhanth718** [shivang8/Secure-File-Storage-Using-Hybrid-Cryptography#10]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Python27\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\SID\Documents\7th Sem Books\PDL lab\Secure-File-Storage-Using-Hybrid-Cryptography\Secure-File-Storage-Using-Hybrid-Cryptography-master\app.py", line 106, in upload_key
    return start_decryption()
  File "C:\Users\SID\Documents\7th Sem Books\PDL lab\Secure-File-Storage-Using-Hybrid-Cryptography\Secure-File-Storage-Using-Hybrid-Cryptography-master\app.py", line 31, in start_decryption
    dec.decrypter()
  File "C:\Users\SID\Documents\7th Sem Books\PDL lab\Secure-File-Storage-Using-Hybrid-Cryptography\Secure-File-Storage-Using-Hybrid-Cryptography-master\decrypter.py", line 85, in decrypter
    secret_information = Algo1(key_1)
  File "C:\Users\SID\Documents\7th Sem Books\PDL lab\Secure-File-Storage-Using-Hybrid-Cryptography\Secure-File-Storage-Using-Hybrid-Cryptography-master\decrypter.py", line 13, in Algo1
    data = f.decrypt(secret_data)
  File "C:\Python27\lib\site-packages\cryptography\fernet.py", line 76, in decrypt
    return self._decrypt_data(data, timestamp, ttl, int(time.time()))
  File "C:\Python27\lib\site-packages\cryptography\fernet.py", line 125, in _decrypt_data
    self._verify_signature(data)
  File "C:\Python27\lib\site-packages\cryptography\fernet.py", line 115, in _verify_signature
    raise InvalidToken
InvalidToken

**Comment by harshravjiani** [comment]
did you solve this error?

**Comment by Aakashgond759** [comment]
how to solve this can anyone help?

**Comment by harshravjiani** [comment]
Yes plz help
